#FILTROS Y CONDICIONALES
#WHERE Y OPERADORES BOOLEANOS
#APLICACION AND / OR/ BETWEEN / IN /LIKE / IS NULL /NOT 
#NOMBRE DE PROVEEDOR, ORDENADOS, CONTENGA INICIO SPORT o BIKE
#CON RANTING CREDITICIO 1 
SELECT Name AS Nombre_empresa,
		CreditRating AS Riesgo
FROM vendor
WHERE CreditRating =1
		and (Name LIKE "Sport%" 
	OR Name LIKE "%Bike%")
ORDER BY	1  
