#TABLA TEMPORAL
#Este script permite generar una CONSULTA 2 PAISES CON MAYOR NIVEL DE VENTAS PARA CADA AÑO
#SE NECESITA AÑO, PAIS/ TERRITORIO, TOTAL DE VTAS Y RANKING
#SI TIENEN VTAS=, AISGNA MISMO RANKING Y NO SALTAR EL CONSECUTIVO

DROP TEMPORARY TABLE IF EXISTS TAB_MONT;
CREATE TEMPORARY TABLE TAB_MONT AS
SELECT	YEAR(OrderDate) AS AÑO_OC,
        o.TerritoryID,
        NAME,
        round(SUM(TotalDue),2) AS TOTAL_AÑO,
        DENSE_RANK() OVER (PARTITION  BY YEAR (OrderDate) ORDER BY SUM(TotalDue) DESC) AS RANKING_MONTO
FROM	salesorderheader o
LEFT JOIN salesterritory t
		ON o.TerritoryID= t.TerritoryID
Group BY 1,2;

SELECT	*
FROM TAB_MONT
WHERE RANKING_MONTO<=2